[dc]
DC01 ansible_host=192.168.10.128

[file_server]
FS01 ansible_host=192.168.10.129

[web]
WEB01 ansible_host=192.168.10.130

[clients]
WS01 ansible_host=192.168.10.131
WS02 ansible_host=192.168.10.140


[all:vars]
ansible_user=Administrator
ansible_password=Salam@123
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
ansible_winrm_operation_timeout_sec=1200
ansible_winrm_read_timeout_sec=1500